//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Download
    {
        public int Id { get; set; }
        public long RepositoryID { get; set; }
        public string Path { get; set; }
        public string Content { get; set; }

        public string GetDirectory() => Path.Substring(0, Path.LastIndexOf('/') + 1).TrimEnd('/');
    }
}
