//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sourse
    {
        public long RepositoryID { get; set; }
        public string Url { get; set; }
        public string Language { get; set; }
    }
}
